# SHAPE enabled-RNA-RNA interaction prediction

In [32]:
import os
import pandas as pd

PATH_VRNA = '../src/ViennaRNA-shape/src/bin/'
plfold_bin = os.path.join(PATH_VRNA,'RNAplfold')
plfold_ARGS = '-u 200 -L 200 -W 200 --shapeMethod Z'

intarna_ARGS = "-n 5 --outOverlap=Q --outMode=C --seedBP=5"
# This should print vrna version
! $plfold_bin --version

RNAplfold 2.4.3

## Run plfold on query RNA U1

In [2]:
fasta_U1 = '../data/2018010-U1-SHAPE/ENSRNA049495626/ENSRNA049495626-T1-U1.fa'
react_U1 = '../data/2018010-U1-SHAPE/ENSRNA049495626/ENSRNA049495626-T1-U1.react'
idprefix = "jupyter-ENSRNA049495626-T1-U1"
! $plfold_bin $plfold_ARGS --shape=$react_U1 --id-prefix $idprefix < $fasta_U1

WARNING: window size 200 larger than sequence length 164

## Run IntaRNA

In [34]:
subopt_csv = idprefix+"_intarna.csv"
heatmap_csv = idprefix+"_heatmap.csv"

In [37]:
! /home/milad/miniconda3/envs/intaSHAPE/bin/IntaRNA $intarna_ARGS --target=../data/ACT1/ACT1-full-genomic-range.fasta --query $fasta_U1 --out="pMinE:"$heatmap_csv --out=$subopt_csv

In [41]:
df_subopts = pd.read_csv(subopt_csv,sep=';')
df_subopts

,id1,start1,end1,id2,start2,end2,subseqDP,hybridDP,E
0,ACT1-full-2621bases,1348,1387,ENSRNA049495626-T1-U1,105,140,CCCCUGCUAUGUAUGUGGCUAUUCAGGCUGUUCUUUCUCU&AGAGG...,(((((((((((...(((((.....((((...(((((((((&)))))...,-10.57610
1,ACT1-full-2621bases,2519,2528,ENSRNA049495626-T1-U1,105,114,CUCUUCCUCU&AGAGGAAGAG,((((((((((&)))))))))),-9.31024
2,ACT1-full-2621bases,418,431,ENSRNA049495626-T1-U1,139,152,CGAACACACACCCC&GGGGUUUGCGUUCG,(((((.((.(((((&))))).)).))))),-9.25116
3,ACT1-full-2621bases,264,273,ENSRNA049495626-T1-U1,76,84,UACUCCUCCC&GGGAGGGUG,(((.((((((&))))))))),-9.03445
4,ACT1-full-2621bases,305,311,ENSRNA049495626-T1-U1,76,82,UCCUCCC&GGGAGGG,(((((((&))))))),-9.01196

In [43]:
TAIR_gff = '/home/milad/1DataBase/TAIR/GCF_000001735.3_TAIR10_genomic.gff.gz'
! gunzip -c $TAIR_gff | grep "gene=ACT1" > ACT1.gff

In [54]:
! head -1 ACT1.gff

NC_003071.7	RefSeq	gene	15778941	15781561	.	+	.	ID=gene14607;Dbxref=Araport:AT2G37620,TAIR:AT2G37620,GeneID:818339;Name=ACT1;Note=Member of the actin gene family. Expressed in mature pollen.;gbkey=Gene;gene=ACT1;gene_biotype=protein_coding;gene_synonym=AAc1,actin 1,ARABIDOPSIS ACTIN 1,F13M22.12,F13M22_12;locus_tag=AT2G37620

In [61]:
df_gff = pd.read_csv('ACT1.gff', sep='\t',header=None,
                     names=['seqname','source','feature','start','end','score','strand','frame','attribute'])
df_gff

,seqname,source,feature,start,end,score,strand,frame,attribute
0,NC_003071.7,RefSeq,gene,15778941,15781561,.,+,.,"ID=gene14607;Dbxref=Araport:AT2G37620,TAIR:AT2..."
1,NC_003071.7,RefSeq,mRNA,15778941,15781561,.,+,.,ID=rna22956;Parent=gene14607;Dbxref=TAIR:AT2G3...
2,NC_003071.7,RefSeq,exon,15778941,15779327,.,+,.,ID=id124338;Parent=rna22956;Dbxref=TAIR:AT2G37...
3,NC_003071.7,RefSeq,exon,15779751,15779820,.,+,.,ID=id124339;Parent=rna22956;Dbxref=TAIR:AT2G37...
4,NC_003071.7,RefSeq,exon,15779957,15780350,.,+,.,ID=id124340;Parent=rna22956;Dbxref=TAIR:AT2G37...
5,NC_003071.7,RefSeq,exon,15780451,15781064,.,+,.,ID=id124341;Parent=rna22956;Dbxref=TAIR:AT2G37...
6,NC_003071.7,RefSeq,exon,15781176,15781561,.,+,.,ID=id124342;Parent=rna22956;Dbxref=TAIR:AT2G37...
7,NC_003071.7,RefSeq,CDS,15779761,15779820,.,+,0,ID=cds18150;Parent=rna22956;Dbxref=Araport:AT2...
8,NC_003071.7,RefSeq,CDS,15779957,15780350,.,+,0,ID=cds18150;Parent=rna22956;Dbxref=Araport:AT2...
9,NC_003071.7,RefSeq,CDS,15780451,15781064,.,+,2,ID=cds18150;Parent=rna22956;Dbxref=Araport:AT2...
10,NC_003071.7,RefSeq,CDS,15781176,15781241,.,+,0,ID=cds18150;Parent=rna22956;Dbxref=Araport:AT2...
11,NC_003071.7,RefSeq,mRNA,15779184,15781561,.,+,.,ID=rna22957;Parent=gene14607;Dbxref=TAIR:AT2G3...
12,NC_003071.7,RefSeq,exon,15779184,15779327,.,+,.,ID=id124343;Parent=rna22957;Dbxref=TAIR:AT2G37...
13,NC_003071.7,RefSeq,exon,15779755,15779820,.,+,.,ID=id124344;Parent=rna22957;Dbxref=TAIR:AT2G37...
14,NC_003071.7,RefSeq,exon,15779957,15780350,.,+,.,ID=id124345;Parent=rna22957;Dbxref=TAIR:AT2G37...
15,NC_003071.7,RefSeq,exon,15780451,15781064,.,+,.,ID=id124346;Parent=rna22957;Dbxref=TAIR:AT2G37...
16,NC_003071.7,RefSeq,exon,15781176,15781561,.,+,.,ID=id124347;Parent=rna22957;Dbxref=TAIR:AT2G37...
17,NC_003071.7,RefSeq,CDS,15779761,15779820,.,+,0,ID=cds18151;Parent=rna22957;Dbxref=Araport:AT2...
18,NC_003071.7,RefSeq,CDS,15779957,15780350,.,+,0,ID=cds18151;Parent=rna22957;Dbxref=Araport:AT2...
19,NC_003071.7,RefSeq,CDS,15780451,15781064,.,+,2,ID=cds18151;Parent=rna22957;Dbxref=Araport:AT2...
20,NC_003071.7,RefSeq,CDS,15781176,15781241,.,+,0,ID=cds18151;Parent=rna22957;Dbxref=Araport:AT2...
21,NC_003071.7,RefSeq,mRNA,15779234,15781561,.,+,.,ID=rna22958;Parent=gene14607;Dbxref=GeneID:818...
22,NC_003071.7,RefSeq,exon,15779234,15779489,.,+,.,ID=id124348;Parent=rna22958;Dbxref=GeneID:8183...
23,NC_003071.7,RefSeq,exon,15779751,15779820,.,+,.,ID=id124349;Parent=rna22958;Dbxref=GeneID:8183...
24,NC_003071.7,RefSeq,exon,15779957,15780350,.,+,.,ID=id124350;Parent=rna22958;Dbxref=GeneID:8183...
25,NC_003071.7,RefSeq,exon,15780451,15781064,.,+,.,ID=id124351;Parent=rna22958;Dbxref=GeneID:8183...
26,NC_003071.7,RefSeq,exon,15781176,15781561,.,+,.,ID=id124352;Parent=rna22958;Dbxref=GeneID:8183...
27,NC_003071.7,RefSeq,CDS,15779761,15779820,.,+,0,ID=cds18152;Parent=rna22958;Dbxref=Araport:AT2...
28,NC_003071.7,RefSeq,CDS,15779957,15780350,.,+,0,ID=cds18152;Parent=rna22958;Dbxref=Araport:AT2...
29,NC_003071.7,RefSeq,CDS,15780451,15781064,.,+,2,ID=cds18152;Parent=rna22958;Dbxref=Araport:AT2...
...,...,...,...,...,...,...,...,...,...
44,NC_003074.8,RefSeq,exon,3858106,3858175,.,+,.,ID=id152442;Parent=rna27810;Dbxref=TAIR:AT3G12...
45,NC_003074.8,RefSeq,exon,3858288,3858681,.,+,.,ID=id152443;Parent=rna27810;Dbxref=TAIR:AT3G12...
46,NC_003074.8,RefSeq,exon,3858837,3859450,.,+,.,ID=id152444;Parent=rna27810;Dbxref=TAIR:AT3G12...
47,NC_003074.8,RefSeq,exon,3859544,3860089,.,+,.,ID=id152445;Parent=rna27810;Dbxref=TAIR:AT3G12...
48,NC_003074.8,RefSeq,CDS,3858116,3858175,.,+,0,ID=cds22414;Parent=rna27810;Dbxref=TAIR:AT3G12...
49,NC_003074.8,RefSeq,CDS,3858288,3858681,.,+,0,ID=cds22414;Parent=rna27810;Dbxref=TAIR:AT3G12...
50,NC_003074.8,RefSeq,CDS,3858837,3859450,.,+,2,ID=cds22414;Parent=rna27810;Dbxref=TAIR:AT3G12...
51,NC_003074.8,RefSeq,CDS,3859544,3859609,.,+,0,ID=cds22414;Parent=rna27810;Dbxref=TAIR:AT3G12...
52,NC_003074.8,RefSeq,gene,17128211,17131466,.,+,.,"ID=gene21406;Dbxref=Araport:AT3G46520,TAIR:AT3..."
53,NC_003074.8,RefSeq,mRNA,17128211,17131466,.,+,.,ID=rna33591;Parent=gene21406;Dbxref=GeneID:823...
54,NC_003074.8,RefSeq,exon,17128211,17128338,.,+,.,ID=id180078;Parent=rna33591;Dbxref=GeneID:8238...
55,NC_003074.8,RefSeq,exon,17128553,17128626,.,+,.,ID=id180079;Parent=rna33591;Dbxref=GeneID:8238...
56,NC_003074.8,RefSeq,exon,17128709,17129102,.,+,.,ID=id180080;Parent=rna33591;Dbxref=GeneID:8238...
57,NC_003074.8,RefSeq,exon,17129202,17129815,.,+,.,ID=id180081;Parent=rna33591;Dbxref=GeneID:8238...
58,NC_003074.8,RefSeq,exon,17129916,17130009,.,+,.,ID=id180082;Parent=rna33591;Dbxref=GeneID:8238...
59,NC_003074.8,RefSeq,exon,17130537,17131466,.,+,.,ID=id180083;Parent=rna33591;Dbxref=GeneID:8238...
60,NC_003074.8,RefSeq,CDS,17128567,17128626,.,+,0,ID=cds26566;Parent=rna33591;Dbxref=GeneID:8238...
61,NC_003074.8,RefSeq,CDS,17128709,17129102,.,+,0,ID=cds26566;Parent=rna33591;Dbxref=GeneID:8238...
62,NC_003074.8,RefSeq,CDS,17129202,17129815,.,+,2,ID=cds26566;Parent=rna33591;Dbxref=GeneID:8238...
63,NC_003074.8,RefSeq,CDS,17129916,17129981,.,+,0,ID=cds26566;Parent=rna33591;Dbxref=GeneID:8238...
64,NC_003074.8,RefSeq,mRNA,17128211,17130412,.,+,.,ID=rna33592;Parent=gene21406;Dbxref=TAIR:AT3G4...
65,NC_003074.8,RefSeq,exon,17128211,17128338,.,+,.,ID=id180084;Parent=rna33592;Dbxref=TAIR:AT3G46...
66,NC_003074.8,RefSeq,exon,17128553,17128626,.,+,.,ID=id180085;Parent=rna33592;Dbxref=TAIR:AT3G46...
67,NC_003074.8,RefSeq,exon,17128709,17129102,.,+,.,ID=id180086;Parent=rna33592;Dbxref=TAIR:AT3G46...
68,NC_003074.8,RefSeq,exon,17129202,17129815,.,+,.,ID=id180087;Parent=rna33592;Dbxref=TAIR:AT3G46...
69,NC_003074.8,RefSeq,exon,17129916,17130412,.,+,.,ID=id180088;Parent=rna33592;Dbxref=TAIR:AT3G46...
70,NC_003074.8,RefSeq,CDS,17128567,17128626,.,+,0,ID=cds26567;Parent=rna33592;Dbxref=TAIR:AT3G46...
71,NC_003074.8,RefSeq,CDS,17128709,17129102,.,+,0,ID=cds26567;Parent=rna33592;Dbxref=TAIR:AT3G46...
72,NC_003074.8,RefSeq,CDS,17129202,17129815,.,+,2,ID=cds26567;Parent=rna33592;Dbxref=TAIR:AT3G46...
73,NC_003074.8,RefSeq,CDS,17129916,17129981,.,+,0,ID=cds26567;Parent=rna33592;Dbxref=TAIR:AT3G46...

In [120]:
print ("Genes with same name (isoforms?)")
df_gff[df_gff['feature']=='gene']

Genes with same name (isoforms?)

,seqname,source,feature,start,end,score,strand,frame,attribute
0,NC_003071.7,RefSeq,gene,15778941,15781561,.,+,.,"ID=gene14607;Dbxref=Araport:AT2G37620,TAIR:AT2..."
41,NC_003074.8,RefSeq,gene,3857780,3860089,.,+,.,"ID=gene17414;Dbxref=Araport:AT3G12110,TAIR:AT3..."
52,NC_003074.8,RefSeq,gene,17128211,17131466,.,+,.,"ID=gene21406;Dbxref=Araport:AT3G46520,TAIR:AT3..."

In [112]:
df_gff_exons = df_gff[df_gff['feature']=='exon'].sort_values('start')
df_gff_exons_uniqs = df_gff_exons.drop_duplicates(subset=['start','end']).copy()
df_gff_exons_uniqs

,seqname,source,feature,start,end,score,strand,frame,attribute
43,NC_003074.8,RefSeq,exon,3857780,3857943,.,+,.,ID=id152441;Parent=rna27810;Dbxref=TAIR:AT3G12...
44,NC_003074.8,RefSeq,exon,3858106,3858175,.,+,.,ID=id152442;Parent=rna27810;Dbxref=TAIR:AT3G12...
45,NC_003074.8,RefSeq,exon,3858288,3858681,.,+,.,ID=id152443;Parent=rna27810;Dbxref=TAIR:AT3G12...
46,NC_003074.8,RefSeq,exon,3858837,3859450,.,+,.,ID=id152444;Parent=rna27810;Dbxref=TAIR:AT3G12...
47,NC_003074.8,RefSeq,exon,3859544,3860089,.,+,.,ID=id152445;Parent=rna27810;Dbxref=TAIR:AT3G12...
2,NC_003071.7,RefSeq,exon,15778941,15779327,.,+,.,ID=id124338;Parent=rna22956;Dbxref=TAIR:AT2G37...
12,NC_003071.7,RefSeq,exon,15779184,15779327,.,+,.,ID=id124343;Parent=rna22957;Dbxref=TAIR:AT2G37...
22,NC_003071.7,RefSeq,exon,15779234,15779489,.,+,.,ID=id124348;Parent=rna22958;Dbxref=GeneID:8183...
3,NC_003071.7,RefSeq,exon,15779751,15779820,.,+,.,ID=id124339;Parent=rna22956;Dbxref=TAIR:AT2G37...
13,NC_003071.7,RefSeq,exon,15779755,15779820,.,+,.,ID=id124344;Parent=rna22957;Dbxref=TAIR:AT2G37...
34,NC_003071.7,RefSeq,exon,15779957,15780350,.,+,.,ID=id124355;Parent=rna22959;Dbxref=GeneID:8183...
25,NC_003071.7,RefSeq,exon,15780451,15781064,.,+,.,ID=id124351;Parent=rna22958;Dbxref=GeneID:8183...
6,NC_003071.7,RefSeq,exon,15781176,15781561,.,+,.,ID=id124342;Parent=rna22956;Dbxref=TAIR:AT2G37...
54,NC_003074.8,RefSeq,exon,17128211,17128338,.,+,.,ID=id180078;Parent=rna33591;Dbxref=GeneID:8238...
55,NC_003074.8,RefSeq,exon,17128553,17128626,.,+,.,ID=id180079;Parent=rna33591;Dbxref=GeneID:8238...
56,NC_003074.8,RefSeq,exon,17128709,17129102,.,+,.,ID=id180080;Parent=rna33591;Dbxref=GeneID:8238...
68,NC_003074.8,RefSeq,exon,17129202,17129815,.,+,.,ID=id180087;Parent=rna33592;Dbxref=TAIR:AT3G46...
58,NC_003074.8,RefSeq,exon,17129916,17130009,.,+,.,ID=id180082;Parent=rna33591;Dbxref=GeneID:8238...
69,NC_003074.8,RefSeq,exon,17129916,17130412,.,+,.,ID=id180088;Parent=rna33592;Dbxref=TAIR:AT3G46...
59,NC_003074.8,RefSeq,exon,17130537,17131466,.,+,.,ID=id180083;Parent=rna33591;Dbxref=GeneID:8238...

In [113]:
gene_start = 15778941
df_gff_exons_uniqs.loc[:,'relative-start']= df_gff_exons_uniqs['start'] - gene_start
df_gff_exons_uniqs.loc[:,'relative-end'] =  df_gff_exons_uniqs['end'] - gene_start

In [123]:
df_gff_exons_uniqs[['relative-start','relative-end']]

    relative-start  relative-end
43       -11921161     -11920998
44       -11920835     -11920766
45       -11920653     -11920260
46       -11920104     -11919491
47       -11919397     -11918852
2                0           386
12             243           386
22             293           548
3              810           879
13             814           879
34            1016          1409
25            1510          2123
6             2235          2620
54         1349270       1349397
55         1349612       1349685
56         1349768       1350161
68         1350261       1350874
58         1350975       1351068
69         1350975       1351471
59         1351596       1352525

In [115]:
#What is going on with duplicated exons?
print ('\n'.join([s.replace(';',' ') for s in df_gff_exons[df_gff_exons['start']==15779957].iloc[:,8]]))

ID=id124355 Parent=rna22959 Dbxref=GeneID:818339,Genbank:NM_001336665.1,Araport:AT2G37620,TAIR:AT2G37620 gbkey=mRNA gene=ACT1 orig_protein_id=gnl|JCVI|AT2G37620.4 orig_transcript_id=gnl|JCVI|mRNA.AT2G37620.4 product=actin 1 transcript_id=NM_001336665.1
ID=id124340 Parent=rna22956 Dbxref=TAIR:AT2G37620,GeneID:818339,Genbank:NM_179953.3,Araport:AT2G37620 gbkey=mRNA gene=ACT1 inference=similar to RNA sequence%2C mRNA:INSD:AY074873.1%2CINSD:AY093784.1%2CINSD:AY089032.1 orig_protein_id=gnl|JCVI|AT2G37620.1 orig_transcript_id=gnl|JCVI|mRNA.AT2G37620.1 product=actin 1 transcript_id=NM_179953.3
ID=id124350 Parent=rna22958 Dbxref=GeneID:818339,Genbank:NM_001336664.1,Araport:AT2G37620,TAIR:AT2G37620 gbkey=mRNA gene=ACT1 orig_protein_id=gnl|JCVI|AT2G37620.3 orig_transcript_id=gnl|JCVI|mRNA.AT2G37620.3 product=actin 1 transcript_id=NM_001336664.1
ID=id124345 Parent=rna22957 Dbxref=TAIR:AT2G37620,GeneID:818339,Genbank:NM_001036427.3,Araport:AT2G37620 gbkey=mRNA gene=ACT1 inference=similar to RNA sequence%2C mRNA:INSD:AY093784.1 orig_protein_id=gnl|JCVI|AT2G37620.2 orig_transcript_id=gnl|JCVI|mRNA.AT2G37620.2 product=actin 1 transcript_id=NM_001036427.3